apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
      - name: node-backend
        image: vijay7823/backend-image
        ports:
        - containerPort: 3000
        env:
        - name: PGUSER
          value: "postgres"
        - name: PGPASSWORD
          value: "password"
        - name: PGDATABASE
          value: "people"
        - name: PGHOST
          value: "postgres-service"
        - name: PGPORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: node-backend
