apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-backend-service
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
  selector:
    {{- include "myapp.selectorLabels" . | nindent 4 }}
    app: node-backend
