# templates/deployment.yaml

# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.environment }}-backend
spec:
  replicas: {{ index .Values .Values.global.environment "replicas" | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.global.environment }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.global.environment }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.global.backend.image }}:{{ index .Values .Values.global.environment "backend" "imageTag" }}"
          ports:
            - containerPort: {{ .Values.global.backend.port }}
          env:
            - name: NODE_ENV
              value: "{{ index .Values .Values.global.environment "backend" "env" "NODE_ENV" }}"
            - name: PGUSER
              value: "{{ index .Values .Values.global.environment "backend" "env" "PGUSER" }}"
            - name: PGPASSWORD
              value: "{{ index .Values .Values.global.environment "backend" "env" "PGPASSWORD" }}"
            - name: PGDATABASE
              value: "{{ index .Values .Values.global.environment "backend" "env" "PGDATABASE" }}"
            - name: PGHOST
              value: "{{ index .Values .Values.global.environment "backend" "env" "PGHOST" }}"
            - name: PGPORT
              value: "{{ index .Values .Values.global.environment "backend" "env" "PGPORT" }}"

---

# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.environment }}-frontend
spec:
  replicas: {{ index .Values .Values.global.environment "replicas" | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.global.environment }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.global.environment }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.global.frontend.image }}:{{ index .Values .Values.global.environment "frontend" "imageTag" }}"
          ports:
            - containerPort: {{ .Values.global.frontend.port }}

---

# PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.environment }}-postgres
spec:
  replicas: {{ index .Values .Values.global.environment "postgres" "replicaCount" | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.global.environment }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.global.environment }}-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.global.postgres.image }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "{{ index .Values .Values.global.environment "postgres" "credentials" "username" }}"
            - name: POSTGRES_PASSWORD
              value: "{{ index .Values .Values.global.environment "postgres" "credentials" "password" }}"
            - name: POSTGRES_DB
              value: "{{ index .Values .Values.global.environment "postgres" "credentials" "database" }}"

