name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  BACKEND_IMAGE: vijay7823/backend-image
  FRONTEND_IMAGE: vijay7823/frontend-image

jobs:
  deploy:
    runs-on: self-hosted

    env:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      ENVIRONMENT: ${{ github.ref_name }}  # Dev or Staging branch name from the CI trigger

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # Step 3: Set environment-specific variables
      - name: Set Image Tag Based on Branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "IMAGE_TAG=latest-dev" >> $GITHUB_ENV
            echo "VALUES_FILE=mychart/values-dev.yaml" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "IMAGE_TAG=latest-staging" >> $GITHUB_ENV
            echo "VALUES_FILE=mychart/values-staging.yaml" >> $GITHUB_ENV
          fi

      # Step 4: Deploy to Kubernetes using Helm
      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install myapp-${{ env.ENVIRONMENT }} ./mychart \
            -f ${{ env.VALUES_FILE }} \
            --set global.environment=${{ env.ENVIRONMENT }} \
            --set global.backend.image=${{ env.BACKEND_IMAGE }} \
            --set global.backend.imageTag=${{ env.IMAGE_TAG }} \
            --set global.frontend.image=${{ env.FRONTEND_IMAGE }} \
            --set global.frontend.imageTag=${{ env.IMAGE_TAG }}

