# Name of the workflow
name: CI

# When to run this workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Environment variables used across jobs
env:
  BACKEND_IMAGE: vijay7823/backend-image    # Change to your Docker Hub username
  FRONTEND_IMAGE: vijay7823/frontend-image   # Change to your Docker Hub username

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Generate version number from git commit
      - name: Generate Version
        id: version
        run: |
          echo "VERSION=v$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "version=${{ env.VERSION }}" >> $GITHUB_OUTPUT

      # Step 3: Build backend image
      - name: Build Backend
        run: |
          docker build -t ${{ env.BACKEND_IMAGE }}:${{ env.VERSION }} ./backend
          docker tag ${{ env.BACKEND_IMAGE }}:${{ env.VERSION }} ${{ env.BACKEND_IMAGE }}:latest

      # Step 4: Build frontend image
      - name: Build Frontend
        run: |
          docker build -t ${{ env.FRONTEND_IMAGE }}:${{ env.VERSION }} ./frontend
          docker tag ${{ env.FRONTEND_IMAGE }}:${{ env.VERSION }} ${{ env.FRONTEND_IMAGE }}:latest

      # Step 5: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 6: Push images to Docker Hub
      - name: Push Images
        run: |
          docker push ${{ env.BACKEND_IMAGE }}:${{ env.VERSION }}
          docker push ${{ env.BACKEND_IMAGE }}:latest
          docker push ${{ env.FRONTEND_IMAGE }}:${{ env.VERSION }}
          docker push ${{ env.FRONTEND_IMAGE }}:latest
